vich_uploader:
    db_driver: orm

    mappings:
        user_pictures:
            uri_prefix: /assets/images/userPictures
            upload_destination: '%kernel.project_dir%/public/assets/images/userPictures'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
    #        namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
